# cargar las bases de datos

In [1]:
import pandas as pd

In [2]:
ruta_carpeta = r"G:\Mi unidad\Data Science - Henry\Data Science - Henry\Modulo 2\Lectures\FoodTrucks\foodtrack-db\data"

In [3]:
ruta_foodtrucks = ruta_carpeta + r"\foodtrucks.csv"

df_foodtrucks = pd.read_csv(ruta_foodtrucks)

df_foodtrucks.head()

   foodtruck_id         name cuisine_type              city
0             1    Taco Loco     Mexicana  Ciudad de México
1             2  Burger Bros    Americana      Buenos Aires

In [4]:
df_foodtrucks.set_index('foodtruck_id', inplace=True)

In [5]:
display(df_foodtrucks)

                     name cuisine_type              city
foodtruck_id
1               Taco Loco     Mexicana  Ciudad de México
2             Burger Bros    Americana      Buenos Aires

In [6]:
ruta_locations = ruta_carpeta + r"\locations.csv"

df_locations = pd.read_csv(ruta_locations, parse_dates=['location_date'])

df_locations.head()

   location_id  foodtruck_id location_date    zone
0            1             1    2023-09-01  Centro
1            2             2    2023-09-01  Parque

In [7]:
df_locations.set_index('location_id', inplace=True)

In [8]:
display(df_locations)

             foodtruck_id location_date    zone
location_id
1                       1    2023-09-01  Centro
2                       2    2023-09-01  Parque

In [9]:
ruta_order_items = ruta_carpeta + r"\order_items.csv"

df_order_items = pd.read_csv(ruta_order_items)

df_order_items.head()

   order_item_id  order_id  product_id  quantity
0              1      1001         101         1
1              2      1002         103         1
2              3      1002         104         1

In [10]:
ruta_orders = ruta_carpeta + r"\orders.csv"

df_orders = pd.read_csv(ruta_orders, parse_dates=['order_date'])

df_orders.head()

   order_id  foodtruck_id order_date     status  total
0      1001             1 2023-09-01  entregado     90
1      1002             2 2023-09-01  pendiente    100

In [11]:
df_orders.set_index('order_id', inplace=True)

In [12]:
display(df_orders)

          foodtruck_id order_date     status  total
order_id
1001                 1 2023-09-01  entregado     90
1002                 2 2023-09-01  pendiente    100

In [13]:
ruta_products = ruta_carpeta + r"\products.csv"

df_products = pd.read_csv(ruta_products)

df_products.head()

   product_id  foodtruck_id            name  price  stock
0         101             1  Taco al pastor     50    100
1         102             1      Quesadilla     40     80
2         103             2    Cheeseburger     70    120
3         104             2    Papas fritas     30    150

In [14]:
df_products.set_index('product_id',inplace=True)

In [15]:
display(df_products)

            foodtruck_id            name  price  stock
product_id
101                    1  Taco al pastor     50    100
102                    1      Quesadilla     40     80
103                    2    Cheeseburger     70    120
104                    2    Papas fritas     30    150